version: "3.7"

services:
  mosquitto:
    container_name: mqtt
    image: docker.io/library/eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./config:/mosquitto/config:Z
      - ./data:/mosquitto/data:Z
      - ./log:/mosquitto/log:Z
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - dockernet

  app:
    image: docker.io/rjonmarco/mqtt-node:0.1
    container_name: mqtt-node
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
    networks:
      - dockernet

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data:Z
      - ./pb_public:/pb_public:Z #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dockernet
  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - dockernet

  mqtt-exporter:
    image: kpetrem/mqtt-exporter
    container_name: mqtt-exporter
    ports:
      - 9000:9000
    environment:
      - MQTT_ADDRESS=mqtt
      - TOPIC_LABEL=powerdata
    restart: unless-stopped
    networks:
      - dockernet
  
  victoriametrics:
    image: docker.io/victoriametrics/victoria-metrics
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - "8428:8428"
    volumes:
      - victoriametrics-storage:/victoria-metrics-data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
    networks:
      - dockernet

volumes:
  victoriametrics-storage:
  prometheus.yml:
  grafana-storage:
  config:
  data:
  log:
  pb_data:
  pb_public:

networks:
  dockernet:
